// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Edit Profile', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Edit Profile', async function() {
    await driver.get("http://localhost:5173/home")
    await driver.manage().window().setRect({ width: 1936, height: 1096 })
    await driver.findElement(By.linkText("Profile")).click()
    {
      const element = await driver.findElement(By.linkText("Profile"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".border-slate-400")).click()
    await driver.findElement(By.id("name")).click()
    await driver.findElement(By.id("name")).sendKeys("Rajat Nai")
    await driver.findElement(By.css(".w-\\[100\\%\\]")).click()
    await driver.findElement(By.css(".ml-4 > svg")).click()
  })
})
