// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Like and Comment', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Like and Comment', async function() {
    await driver.get("http://localhost:5173/home")
    await driver.manage().window().setRect({ width: 1936, height: 1096 })
    await driver.findElement(By.css(".w-full:nth-child(1) .w-full:nth-child(1) > .text-xl")).click()
    await driver.findElement(By.css(".w-full:nth-child(1) .w-full:nth-child(2) > .text-xl")).click()
    await driver.findElement(By.name("comment")).click()
    await driver.findElement(By.name("comment")).sendKeys("We all are fine!!")
    await driver.findElement(By.css(".w-full:nth-child(1) > .h-20 svg")).click()
    await driver.findElement(By.css(".w-full:nth-child(1) > .border-b-2:nth-child(2) > .w-full")).click()
    await driver.findElement(By.css(".m-4")).click()
    await driver.findElement(By.css(".w-full:nth-child(1) > .border-b-2:nth-child(2) > .w-full")).click()
    await driver.findElement(By.css(".w-8 > path")).click()
  })
})
