// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('User Login', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('User Login', async function() {
    await driver.get("http://localhost:5173/home/")
    await driver.manage().window().setRect({ width: 974, height: 1080 })
    await driver.findElement(By.css(".text-orange-400")).click()
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).sendKeys("rajatnai49@gmail.com")
    await driver.findElement(By.id("password")).click()
    await driver.findElement(By.id("password")).sendKeys("Rajat@#1")
    await driver.findElement(By.id("password")).sendKeys(Key.ENTER)
  })
})
