// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('User Regiter', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('User Regiter', async function() {
    await driver.get("http://localhost:5173/")
    await driver.manage().window().setRect({ width: 1936, height: 1096 })
    await driver.findElement(By.css(".bg-orange-400")).click()
    await driver.findElement(By.css(".h-screen:nth-child(3) .mt-10 img")).click()
    await driver.findElement(By.id("avatar")).sendKeys("C:\\fakepath\\c037c3126d2a9eec910a8724aed0e8fa.jpg")
    await driver.findElement(By.id("name")).click()
    await driver.findElement(By.id("name")).sendKeys("Mandar Parekh")
    await driver.findElement(By.css(".h-screen:nth-child(3) .mt-10 > .flex")).click()
    await driver.findElement(By.css(".h-screen:nth-child(3) #email")).click()
    await driver.findElement(By.css(".h-screen:nth-child(3) #email")).sendKeys("mandar007@gmail.com")
    await driver.findElement(By.css(".h-screen:nth-child(3) #password")).click()
    await driver.findElement(By.css(".h-screen:nth-child(3) #password")).sendKeys("Rajat@#1")
    await driver.findElement(By.css(".h-screen:nth-child(3) > .flex .w-\\[100\\%\\]")).click()
  })
})
